config/routes.rb
Rails.application.routes.draw do
  root 'cars#index'
  resources :manufacturers, only: [:index, :show, :new, :create]
  resources :cars, only: [:index, :show, :new, :create]
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :manufacturer

  validates :year, presence: true, numericality: {
    greater_than: 1919, less_than: 2015
    }
  validates :model, presence: true
  validates :mileage, presence: true, numericality: { greater_than: 0 }
  validates :color, presence: true
  validates :manufacturer, presence: true
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :cars

  validates :name, presence: true, uniqueness: true
  validates :country, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @car = Car.order('created_at DESC')
  end

  def new
    @manufacturer = Manufacturer.all.map { |u| [u.name, u.id] }
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      flash[:notice] = 'Successfully created...'
      redirect_to cars_path
    else
      @manufacturer = Manufacturer.all.map { |u| [u.name, u.id] }
      flash[:notice] = 'There was a problem saving your submission...'
      render :new
    end
  end

  private

  def car_params
    params.require(:car).permit(
      :year, :model, :mileage, :color, :description,
      :manufacturer_id
    )
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  def index
    @manufacturer = Manufacturer.order('name ASC')
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)
    if @manufacturer.save
      flash[:notice] = 'Successfully created...'
      redirect_to manufacturers_path
    else
      flash.now[:notice] = 'There was a problem saving your submission...'
      render :new
    end
  end

  private

  def manufacturer_params
    params.require(:manufacturer).permit(:name, :country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.erb
<h3>Available Automobiles</h3>
<div>
  <ul>
    <% @car.each do |c| %>

      <li>
        Year: <%= c.year %>
      </li>

      <li>
        Make: <%= c.manufacturer.name%>
      </li>

      <li>
        Model: <%= c.model %>
      </li>

      <li>
        Mileage: <%= c.mileage %>
      </li>

      <li>
        Color: <%= c.color %>
      </li>

      <% unless c.description == ''%>
        <li>
          Details: <%= c.description %>
        </li>
      <%end%>
      <br>
    <%end%>
  </ul>
</div>

app/views/cars/new.html.erb
<h3>Enter a Car to Add to Inventory</h3>
<div>
  <%= form_for @car do |f| %>

    <%= f.label :year %>
    <% if @car.errors[:year].any? %>
      <%= @car.errors[:year][0] %>
    <% end %>
    <%= f.text_field :year%>

    <br>
    <%= f.label :manufacturer_id, 'Manufacturer' %>
    <% if @car.errors[:manufacturer_id].any? %>
      <%= @car.errors[:manufacturer_id][0] %>
    <% end %>
    <%= f.select(:manufacturer_id, options_for_select(@manufacturer)) %>
    <%= link_to 'or Add a Manufacturer', new_manufacturer_path%>
    <br><br>

    <%= f.label :model %>
    <% if @car.errors[:model].any? %>
      <%= @car.errors[:model][0] %>
    <% end %>
    <%= f.text_field :model %>

    <br>

    <%= f.label :mileage %>
    <% if @car.errors[:mileage].any? %>
      <%= @car.errors[:mileage][0] %>
    <% end %>
    <%= f.text_field :mileage %>

    <br>

    <%= f.label :color %>
    <% if @car.errors[:color].any? %>
      <%= @car.errors[:color][0] %>
    <% end %>
    <%= f.text_field :color %>

    <br>

    <%= f.label :description %>
    <% if @car.errors[:description].any? %>
      <%= @car.errors[:description][0] %>
    <% end %>
    <%= f.text_field :description %>

    <br>

    <%= f.submit 'Submit'%>

  <%end%>

  <%= link_to 'Back to All Cars', cars_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarListing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <%= link_to 'View all Automobiles', cars_path%>
  |
  <%= link_to 'Available Manufacturers', manufacturers_path%>
  |
  <%= link_to 'Add Manufacturer', new_manufacturer_path%>
  |
  <%= link_to 'Add Automobile', new_car_path %><br>
</nav>
<%= notice %>
<%= yield %>

</body>
</html>

app/views/manufacturers/index.html.erb
<h3>Available Manufacturers</h3>
<ul>
  <% @manufacturer.each do |m| %>
    <li>Make: <%= m.name %></li>
    <li>Country: <%= m.country %></li>
  <br>
  <%end%>
</ul>

app/views/manufacturers/new.html.erb
<h3>Enter a Manufacturer Description</h3>
<div>
  <%= form_for @manufacturer do |f| %>

    <%= f.label :name%>
    <% if @manufacturer.errors[:name].any? %>
      <%= @manufacturer.errors[:name][0] %>
    <% end %>
    <%= f.text_field :name%>

    <br>

    <%= f.label :country%>
    <% if @manufacturer.errors[:country].any? %>
      <%= @manufacturer.errors[:country][0] %>
    <% end %>
    <%= f.text_field :country%>

    <br>

    <%= f.submit 'Submit'%>

  <%end%>
</div>